[project]
name = "pyControl"
version = "1.8.1"
dependencies = ["numpy", "pyserial", "PyQt6", "pyqtgraph"]
[tool.black]
line-length = 120
[tool.setuptools.packages.find]
exclude = ["data", "experiments", "tests"]
